Description: CD12352 - Infrastructure as Code Project - Udagram

Parameters:
  EnvironmentName:
    Description: Environment name used as prefix for resources
    Type: String

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro

  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  SSHLocation:
    Description: The IP address range that can be used to SSH
    Type: String
    Default: 0.0.0.0/0


Resources:
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
      InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref WebAppSecurityGroup
        ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 (us-east-1)
        UserData:
          Fn::Base64: |
            #!/bin/bash
            apt-get update -y
            apt-get install nginx -y
            systemctl start nginx
            systemctl enable nginx
            echo "<h1>Udagram is Live!</h1>" > /var/www/html/index.html
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref WebAppLaunchTemplate
        Version: !GetAtt WebAppLaunchTemplate.LatestVersionNumber
      SubnetId:
        Fn::Select:
          - 0
          - Fn::Split:
              - ","
              - Fn::ImportValue: !Sub "${EnvironmentName}-PublicSubnets"
Outputs:
  WebAppPublicIP:
    Description: Public IP of the Udagram web server
    Value: !GetAtt WebAppInstance.PublicIp


        
